Добавлена обработка изображения + обновление конфигурации
makehtml/gulp-boilerplate pull request #4
Opened 2023-04-04 12:07 UTC by niknov80

1. Добавлена обработка изображений
2. Добавлен sourcemap для стилей и скриптов
3. Сделано модульное подключение скриптов
4. Исправлены пути скриптов и стилей для pixelGlass
5. Добавлено удаление папки build перед сборкой

2023-04-05 21:20 UTC, ademaro commented on gulpfile.js
> +import sourcemaps from 'gulp-sourcemaps';
единообразие кавычек + давай в алфавитном порядке)

2023-04-05 21:23 UTC, ademaro commented on gulpfile.js
> +export const img = ()  => src(`${path.img.root}/**/*.{png,jpg}`)
`{png,jpg,jpeg}`

2023-04-05 21:24 UTC, ademaro commented on gulpfile.js
> +  .pipe(sharpOptimizeImages({
давай отдельно вынесем 
```js
    {
      webp: {
        quality: 80,
        lossless: false,
      },
      png_to_png: {
        quality: 80,
        lossless: false,
      },
      jpg_to_jpg: {
        quality: 80,
        mozjpeg: true,
      },
    }
```

2023-04-05 21:26 UTC, ademaro commented on src/static/js/main.js
> +import {test} from "./script.js";
одинарные кавычки в js

2023-04-05 21:26 UTC, ademaro commented on src/templates/base.j2
> +    <script src="{{ url_for('static', filename='../pp/script.js') }}"></script>
папка pp в статике должна быть, не надо на уровень выше делать

2023-04-05 21:28 UTC, ademaro commented on src/templates/base.j2
> +  <script src="{{ url_for('static', filename='js/main.js') }}" type="module"></script>
я бы оставил script.min.js и прикрутил бандлер (сборщик всех модулей в один файл)

для разработки — type=module можно оставить

2023-04-05 21:28 UTC, ademaro requested changes
Пока дорабатываем чутка, но в целом ок)

2023-04-07 11:06 UTC, niknov80 commented on gulpfile.js
> +import sourcemaps from 'gulp-sourcemaps';
Сделал

2023-04-07 11:07 UTC, niknov80 commented on gulpfile.js
> +export const img = ()  => src(`${path.img.root}/**/*.{png,jpg}`)
Добавил

2023-04-07 11:08 UTC, niknov80 commented on gulpfile.js
> +  .pipe(sharpOptimizeImages({
Вынес в отдельную переменную

2023-04-07 11:08 UTC, niknov80 commented on src/static/js/main.js
> +import {test} from "./script.js";
Исправил

2023-04-07 11:09 UTC, niknov80 commented on src/templates/base.j2
> +    <script src="{{ url_for('static', filename='../pp/script.js') }}"></script>
Исправил пути здесь и в gulpfile.js

2023-04-07 11:11 UTC, niknov80 commented on src/templates/base.j2
> +  <script src="{{ url_for('static', filename='js/main.js') }}" type="module"></script>
Добавил сборщик и сделал его в двух режимах dev и build

2023-04-07 12:40 UTC, ademaro commented on gulpfile.js
> +  .pipe(webpack({
я бы не тянул тяжелый вабпак, тем более он жирный бандл делает, можем обсудить что лучше: parcel, rollup, fusebox...

2023-04-07 12:47 UTC, ademaro commented on gulpfile.js
> +  .pipe(webpack({
https://pax.js.org/
https://poi.js.org/

2023-04-08 11:00 UTC, ademaro approved these changes

2023-04-08 11:00 UTC, merged